const enum COLORS {
  //  PRIMARYS
  PRIMARY_MAIN = '#4696ec',

  //  LIGHT TEXT
  TEXT_LIGHT = '#FFFFFF',
  TEXT_PRIMARY = PRIMARY_MAIN,
  TEXT_DARK = '#212121',

  //  SURFACES
  BACKGROUND_LIGHT = '#FFFFFF',
  BACKGROUND_PRIMARY = PRIMARY_MAIN,
  BACKGROUND_DARK = '#000000'
}

export default COLORS;
