const enum COLORS {
  //  PRIMARYS
  PRIMARY_MAIN = '#4696ec',

  //  LIGHT TEXT
  TEXT_LIGHT = '#FFFFFF',
  TEXT_PRIMARY = PRIMARY_MAIN,
  TEXT_DARK = '#212121',

  BORDER_LIGHT = '#CCCCCC',
  BORDER_PRIMARY = PRIMARY_MAIN,
  BORDER_DARK = '#383735',

  //  SURFACES
  BACKGROUND_LIGHT = '#FFFFFF',
  BACKGROUND_PRIMARY = PRIMARY_MAIN,
  BACKGROUND_DARK = '#5c5a55',
  BACKGROUND_DARK_TRANSPARENT = 'rgba(196, 196, 196, 0.7)',
}

export default COLORS;
