const enum ROUTES {
  //  MAIN TAB ROUTES
  CARS_NAVIGATOR = 'CARS_NAVIGATOR',
  INFO_NAVIGATOR = 'INFO_NAVIGATOR',

  // INFO ROUTER SCREENS
  INFO_SCREEN = 'INFO',
  SCAN_DRIVING_LICENSE_SCREEN = 'SCAN_DRIVING_LICENSE_SCREEN',
}

export default ROUTES;
