const enum ROUTES {
  //  MAIN TAB ROUTES
  CARS_NAVIGATOR = 'CARS_NAVIGATOR',
  INFO_NAVIGATOR = 'INFO_NAVIGATOR',
  KAAS_NAVIGATOR = 'KAAS_NAVIGATOR',

  // INFO ROUTER SCREENS
  INFO_SCREEN = 'INFO',
  SCAN_DRIVING_LICENSE_SCREEN = 'SCAN_DRIVING_LICENSE_SCREEN',

  // Kaas SDK
  KAAS_TEST_SCREEN = 'KAAS_TEST_SCREEN',

  // Cars
  CARS_SCREEN = 'CARS_SCREEN',
}

export default ROUTES;
